// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiGJ3obw73RHx4RYJZelH3RN4C7VNCQcQ',
    appId: '1:259574256916:web:a0045ef4f8dc0863c5de01',
    messagingSenderId: '259574256916',
    projectId: 'attendance-system-a10eb',
    authDomain: 'attendance-system-a10eb.firebaseapp.com',
    databaseURL: 'https://attendance-system-a10eb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendance-system-a10eb.appspot.com',
    measurementId: 'G-QH8EHJ95HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4u08WmvqXmUUFxqf6Vc-okGEtYgFnX-A',
    appId: '1:259574256916:android:eb9d593761ce0f31c5de01',
    messagingSenderId: '259574256916',
    projectId: 'attendance-system-a10eb',
    databaseURL: 'https://attendance-system-a10eb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendance-system-a10eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2zzNXoYL4fheSf96UZCkpnE-y4nTmwQQ',
    appId: '1:259574256916:ios:e4292dab354e046cc5de01',
    messagingSenderId: '259574256916',
    projectId: 'attendance-system-a10eb',
    databaseURL: 'https://attendance-system-a10eb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendance-system-a10eb.appspot.com',
    iosBundleId: 'com.example.smartAttendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2zzNXoYL4fheSf96UZCkpnE-y4nTmwQQ',
    appId: '1:259574256916:ios:f5f23357e81e9681c5de01',
    messagingSenderId: '259574256916',
    projectId: 'attendance-system-a10eb',
    databaseURL: 'https://attendance-system-a10eb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendance-system-a10eb.appspot.com',
    iosBundleId: 'com.example.smartattendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiGJ3obw73RHx4RYJZelH3RN4C7VNCQcQ',
    appId: '1:259574256916:web:684cb76239eb9b2bc5de01',
    messagingSenderId: '259574256916',
    projectId: 'attendance-system-a10eb',
    authDomain: 'attendance-system-a10eb.firebaseapp.com',
    databaseURL: 'https://attendance-system-a10eb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendance-system-a10eb.appspot.com',
    measurementId: 'G-BNMQYK6H5F',
  );

}